language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm run lint
- npm test
deploy:
  provider: heroku
  api_key:
    secure: "Hz8KLVd+4AP7SVI+nDvm7VAoaZNozDhiwRrRa+qNBxPmpYGB9mcZWx3VkTWF+PalSl8tKSmoyJZlpcwn3ptNdALWx6Cbi3geDfqpvpZGQ+jqggthz25j71QaIgytb1P1fUrDDR3xcPBYdUBiLhCy0w5luRlFy4qKqjwNLFqznSF0PBLvTLpDGn2CLZHtwPsw9YfC5OSjnD0BbsOjL1yYnGXwDIFVrZFh5X+QQ5sKmJcAbKNs+WHhXP4AJT4oxE4RM9WLjnWaUmcATAkZM+XBMVQ4287QcuBHfu3iRJC+3eBUnQOqhrWJ3nrRJFsVGMmFK7+DJVRiRy+jfmSRcjyIxtnXT0C726e67JfJN7KfVIDEgs3ZUeYdMB4fQoVUmVcCVSCZUuS30ilWp/i84DmbbNkXkSeznGpgLv+zz+VAa5R9GRDaKL/fivWJ/dY82ZNuXy0zI4Ks28ubrp5QN/Dp4ValLh7YV9jkAQdRUlANKQ9RsotftjFS/n1guZxu7bueSAfC3t3rt42WgzyBOcky+8VkQMp1A2koqKgSB59LaUxOoHZRMeAS9TyLtOtlHtOb4ltbJXZYS4+SeMsILS7JFx86Ava2aXMEn///56KCDNeXeAF4SEWslQXkj57Rr9RVidTzLLN56zHbF+kuNcsRd75HrdmB8tPyOpkYMekxAoM="
  app: bloglist-be
  on:
    repo: nigoshh/fusta2018-blogilista-backend
