language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm run lint
- npm test
deploy:
  provider: heroku
  api_key:
    secure: ILIyAJ+gLULmdJvuZ1cBYtQJ5zcNb2aJxTI1FHQT8V1LSSKEG4ypCRy8v+7pfelSn73GYPCdlc8MHchxGcplZv/Ic4169i2gVhtCTyy+2PBXqOHfpdJdITo1b7Keq5HL9JUl2RDq2oQg8KSDboQPj5+A5QlqnfPXKL2VHFcB1r88/fuiA0paE/C56ZG5vUIpxqa75DR/X9xw6WLFywc1WRRMPE9w1mXIvBjL4IP7DrAGo+AjjhvmTEj6E5Inm3osVNGtysAa1P77sdZYL0zoAcamqKmpiC+cAYqF7Xy89k4GlsS+LAEQLKkVhDomcvsWTqp+9QFfoW5yTtXemXQljQfYiFcQxHoKxotyvOq2czQ0sjUGIZcqCTa1Vhs/4i7YzisAL/gfbyjpSAYs9vrr+gRtMDxXAHZByGpzCexAgH9pz9VChtGvtAjlUFlYqNjG5PVPraAGUvDntOHYu9KeZGiyELRJdsiEJeEgvMH9dgeNVfRLdSd8/9717IH2jgIe6gyN+58fJ5Kpm1ofkbfnJnyyXHZXjs+7qJCwjZscfE1g1LWSn4gIu44GDaLwBD9DXzeyav2xuDaevDAr9Po/GD2xuZWIGYfEQFgzMRT3IdEFx6ciOyacC9Tz/NadXkfxeseaKnKr2icoeH9bSBRvwK88647rGbDqBiAYC5MU+/g=
  app: bloglist-be
  on:
    repo: nigoshh/fusta2018-blogilista-backend
