language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm run lint
- npm test
deploy:
  provider: heroku
  api_key:
    secure: jtQ/ascWGniTTpLOz+FbAA8FpAgSSzfj7+yMfP2Iud0rUr016CM65w6EwwiCeEdDnBD4CU2QyF79LreHhIJV1KUPJ5Ve0O1gHXjp+xKEG/w9z2+Q3XNE4DTvYvWqbo5j9i5IYnBFMG7QHH6Bk5Srmx8N/6kp0dfnCmP1mvDGrNLVUseX5Mw5CWk60XEl3Dcc1Ua/AhlFcffyX/C/RSVSSGx615Kq4pJaPDNpbsqdnUyAbegugxNOdqMw2jrOKOJwBpWbxH5W4w4lIbzy8Y46RLDXssEzHixeUswLX6+Lp4mOY1KhSV8d1vi2l2Vpt0m0Ag0dPkpTlgHG5I88Yew/w545iCO+xT2uitolnkDyULljNqUtSkrawLfH9IjHEFMZW57EgZcXITC5L/9jXmaMZRtD4M/imYH+BCzuc23dml6GZyoFqpLuLvu1AROBprslaH+tP9UqYTBwvaMaR5vze/uOXk3Ttne4YI4RvQkUnOLJQV9QVyrY+ftgGmRkN6rKiTSxqmhPIy8tzsshsSqO9YzEgBnZMz1koYpKYUVOhja4ghu+yyztZz4bLT5ZvM8bSVAyF+lasXq+h02fFyJy9YbVZZ0ciRcXOgY+UCOEMCFstk3d9TRjW5ecEdTz7DWtwA5ZTtRA1/mgqchnwpyRoyqXl+Z2S2FeEsitthQUonY=
  app: bloglist-be
  on:
    repo: nigoshh/fusta2018-blogilista-backend
